services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: loyaltyUser
      POSTGRES_DB: loyaltyDB
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    secrets:
      - db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U loyaltyUser -d loyaltyDB || exit 1"]
      interval: 10s
      retries: 5

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/loyaltyDB
      SPRING_DATASOURCE_USERNAME: loyaltyUser
      SPRING_PROFILES_ACTIVE: docker
      QR_SERVICE_URL: http://qr-service:8000
    secrets:
      - jwt_secret
      - db_password
    entrypoint: >
      sh -c "
      export SPRING_DATASOURCE_PASSWORD=$$(cat /run/secrets/db_password | tr -d '\r') &&
      export JWT_SECRET=$$(cat /run/secrets/jwt_secret | tr -d '\r') &&
      java -Djwt.secret=$$JWT_SECRET -jar app.jar
      "
    depends_on:
      postgres:
        condition: service_healthy
      qr-service:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      retries: 5

  qr-service:
    build: ../qr-service/qr-service
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      retries: 5

secrets:
  jwt_secret:
    file: ./secrets/jwt_secret
  db_password:
    file: ./secrets/db_password

volumes:
  pgdata:
