services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: loyaltyUser
      POSTGRES_DB: loyaltyDB
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    secrets:
      - db_password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U loyaltyUser -d loyaltyDB || exit 1"]
      interval: 10s
      retries: 5

  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/loyaltyDB
      SPRING_DATASOURCE_USERNAME: loyaltyUser
      SPRING_PROFILES_ACTIVE: docker
      QR_SERVICE_URL: http://qr-service:8000
    secrets:
      - jwt_secret
      - db_password
      - seed-passwords
    entrypoint: >
      sh -c "
      export SPRING_DATASOURCE_PASSWORD=$$(cat /run/secrets/db_password | tr -d '\r') &&
      export JWT_SECRET=$$(cat /run/secrets/jwt_secret | tr -d '\r') &&
      export APP_SEED_PASSWORDS=$$(cat /run/secrets/seed-passwords) &&
      java -Djwt.secret=$$JWT_SECRET -jar app.jar
      "
    depends_on:
      postgres:
        condition: service_healthy
      qr-service:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "wget -q --spider http://localhost:8080/actuator/health || exit 1"]
      interval: 30s
      retries: 5

  qr-service:
    build: ../qr-service/qr-service
    ports:
      - "8000:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 30s
      retries: 5

  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.enable-lifecycle
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    depends_on:
      - gateway
      - qr-service

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

secrets:
  jwt_secret:
    file: ./secrets/jwt_secret
  db_password:
    file: ./secrets/db_password
  seed-passwords:
    file: ./secrets/seed-passwords

volumes:
  pgdata:
